name: Run pytest

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.7'  # Specify the Python version

      - name: Install dependencies
        run: pip install -r requirements.txt  # Adjust as needed

      - name: Run pytest
        run: pytest
